on:
  repository_dispatch:
    types: [data_updated]

jobs:
  check-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Test input parameters 
        run: |
          echo "Data passed in payload ${{ github.event.client_payload.action }}"
