on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  WORKFLOW_ENV: workflow

jobs:
  log-the-inputs:
    env:
      JOB_ENV: job
    runs-on: ubuntu-latest
    steps:
      - name: Test input parameters 
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "WORKFLOW_ENV: $WORKFLOW_ENV"
          echo "JOB_ENV: $JOB_ENV"
        env:
          LEVEL: inputs.logLevel
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
          
      - name: test-tags 
        if: inputs.tags
        run: echo "Testing tags"
        
